INSERT INTO ChecklistItems (CheckListId, Title, SequenceNumber) 
VALUES 
(1,'Check mouthpiece for tears',1),
(1,'Check mushroom valve',2),
(1,'INSPECT** and lube o-rings on loop',3),
(1,'Turn on computer, note milivolts, do initial math on linearity worksheet and check battery',4),
(1,'Pack scrubber cannisters',5),
(1,'INSTPECT** and lube cannister head o-rings',6),
(1,'Install heads with proper tower alignment',7),
(1,'Install right side cannister with hoses onto harness',8),
(1,'Route O2 hose and 1st stage, connect to O2 bottle',9),
(1,'Install left side cannister onto harness',10),
(1,'INSPECT** and lube counter lung o-rings',11),
(1,'Install counter lung - be sure to install locking clips',12),
(1,'Position counter lung and cannisters outside of waist belt',13),
(1,'Connect bungee loops and cannister bungee retainers',14),
(1,'Verify the EXHALE side (right side) of loop and intall loop onto cannister towers',15),
(1,'Perform negative check',16),
(1,'Plug in offboard O2 to diluent hose',17),
(1,'Add O2 to unit in small spurts via ADV',18),
(1,'Monitor PO2 reading for smooth and even increases',19),
(1,'Once stabilized lightly press ADV and hold for slow flow of O2 and note millivolts and complete the Linearity worksheet',20),
(1,'If needed, calibrate your computer',21),
(1,'Close DSV and perform POSITIVE check and then close valve on O2 and purge remaining O2 into sidewinder',22);
